import { ApiQuery } from "../api/type";

interface SelectedItem {
  id: number;
  name: string;
  parentName: keyof ApiQuery;
}

export const selectedItems: SelectedItem[] = [
  { id: 3, name: "2.0374", parentName: "CODCCUSTO" },
  { id: 8, name: "thales.oliveira", parentName: "USUARIOCRIACAO" },
];


export const DATA: ApiQuery[] = [
  {
    CODCCUSTO: "2.0364",
    NUMEROMOV: "271429",
    DATACRIACAO: "22 jul 2023",
    DATAENTREGA: "22 ago 2023",
    ATRASO: 137,
    CODTMV: "1.1.05",
    CODCFO: "53329",
    NOME: "GARDEIS EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA",
    USUARIOCRIACAO: "cleverton.lima",
    VALORLIQUIDOORIG: 624.0,
    HISTORICOCURTO:
      "AQUISIÇÃO DE EQUIOAMENTOS DE SEGURANÇA PARA LINHA DE TRANSMISSÃO.",
    STATUS: "EXPIRADA",
    IDMOV: 2010981,
    CENTRO_DE_CUSTO:
      "Construção SE 230/69KV/LT 230KV Leilão da ANEEL D.Pedro II",
  },
  {
    CODCCUSTO: "2.0364",
    NUMEROMOV: "271428",
    DATACRIACAO: "22 jul 2023",
    DATAENTREGA: "22 ago 2023",
    ATRASO: 137,
    CODTMV: "1.1.05",
    CODCFO: "53250",
    NOME: "AUTO MECANICA DELTA DIESEL CAMINHÕES",
    USUARIOCRIACAO: "cleverton.lima",
    VALORLIQUIDOORIG: 1318.0,
    HISTORICOCURTO:
      "REFERENTE A SERVIÇOS PARA O CAMINHÃO MUNCK FROTA ENGEPAR CG-02",
    STATUS: "EXPIRADA",
    IDMOV: 2010937,
    CENTRO_DE_CUSTO:
      "Construção SE 230/69KV/LT 230KV Leilão da ANEEL D.Pedro II",
  },
  {
    CODCCUSTO: "2.0364",
    NUMEROMOV: "271427",
    DATACRIACAO: "22 jul 2023",
    DATAENTREGA: "22 ago 2023",
    ATRASO: 137,
    CODTMV: "1.1.05",
    CODCFO: "53250",
    NOME: "AUTO MECANICA DELTA DIESEL CAMINHÕES",
    USUARIOCRIACAO: "cleverton.lima",
    VALORLIQUIDOORIG: 1632.82,
    HISTORICOCURTO:
      "REFERENTE A TROCA DE PEÇAS PARA O CAMINHÃO MUNCK FROTA ENGEPAR CG-02",
    STATUS: "EXPIRADA",
    IDMOV: 2010925,
    CENTRO_DE_CUSTO:
      "Construção SE 230/69KV/LT 230KV Leilão da ANEEL D.Pedro II",
  },
  {
    CODCCUSTO: "2.0364",
    NUMEROMOV: "271424",
    DATACRIACAO: "21 jul 2023",
    DATAENTREGA: "21 ago 2023",
    ATRASO: 138,
    CODTMV: "1.1.05",
    CODCFO: "52721",
    NOME: "LIMPTOP LTDA",
    USUARIOCRIACAO: "cleverton.lima",
    VALORLIQUIDOORIG: 792.0,
    HISTORICOCURTO:
      "AQUISIÇÃO DE BANCOS PLASNTICOS PARA AREA DE VIVENCIA EQUIPES DE LINHA DE TRANSMISSÃO.",
    STATUS: "EXPIRADA",
    IDMOV: 2010738,
    CENTRO_DE_CUSTO:
      "Construção SE 230/69KV/LT 230KV Leilão da ANEEL D.Pedro II",
  },
  {
    CODCCUSTO: "2.0385",
    NUMEROMOV: "271408",
    DATACRIACAO: "21 jul 2023",
    DATAENTREGA: "05 ago 2023",
    ATRASO: 138,
    CODTMV: "1.1.05",
    CODCFO: "20871",
    NOME: "SOLDAMAQ COMERCIO DE FERRAMENTAS LTDA",
    USUARIOCRIACAO: "pedro.souza",
    VALORLIQUIDOORIG: 2780.01,
    HISTORICOCURTO:
      "SOLICITAÇÕES DE MATERIAIS RETIRADOS PELO EMPREITEIRO DIEGO FASSINA SERÁ DESCONTADO EM MEDIÇÃO \r\n\r\nCONTRATO 2.0385-002-2023 S - MHDL CONST. E LOC. DE MAQ. E EQUIP. LTDA",
    STATUS: "EXPIRADA",
    IDMOV: 2010552,
    CENTRO_DE_CUSTO: "Pavimentação Asfáltica ROD MS-278 Caarapó MS - AGESUL",
  },
  {
    CODCCUSTO: "2.0385",
    NUMEROMOV: "271404",
    DATACRIACAO: "21 jul 2023",
    DATAENTREGA: "28 jul 2023",
    ATRASO: 138,
    CODTMV: "1.1.05",
    CODCFO: "20871",
    NOME: "SOLDAMAQ COMERCIO DE FERRAMENTAS LTDA",
    USUARIOCRIACAO: "lucieni.decian",
    VALORLIQUIDOORIG: 645.09,
    HISTORICOCURTO:
      "SOLICITAÇÕES DE MATERIAIS RETIRADOS PELO EMPREITEIRO DIEGO FASSINA SERÁ DESCONTADO EM MEDIÇÃO \r\n\r\nCONTRATO 2.0385-002-2023 S - MHDL CONST. E LOC. DE MAQ. E EQUIP. LTDA",
    STATUS: "EXPIRADA",
    IDMOV: 2010512,
    CENTRO_DE_CUSTO: "Pavimentação Asfáltica ROD MS-278 Caarapó MS - AGESUL",
  },
  {
    CODCCUSTO: "2.0374",
    NUMEROMOV: "000422",
    DATACRIACAO: "21 jul 2023",
    DATAENTREGA: "28 jul 2023",
    ATRASO: 138,
    CODTMV: "1.1.05",
    CODCFO: "09999",
    NOME: "ENGEPAR ENGENHARIA E PARTICIPACOES LTDA",
    USUARIOCRIACAO: "thales.oliveira",
    VALORLIQUIDOORIG: 1423.0,
    HISTORICOCURTO: "Materiais pra uso na obra;",
    STATUS: "EXPIRADA",
    IDMOV: 2010432,
    CENTRO_DE_CUSTO: "Residencial UPFRONT Lagoa Itatiaia CGMS SCP",
  },
  {
    CODCCUSTO: "2.0364",
    NUMEROMOV: "271392",
    DATACRIACAO: "21 jul 2023",
    DATAENTREGA: "21 ago 2023",
    ATRASO: 138,
    CODTMV: "1.1.05",
    CODCFO: "51581",
    NOME: "COMERCIAL ZM IRRIGACAO MAQUINAS E MOTORES EIRELI",
    USUARIOCRIACAO: "cleverton.lima",
    VALORLIQUIDOORIG: 452.6,
    HISTORICOCURTO:
      "AQUISIÇÃO DE MATERIAL PARA DESTOCAMENTO E LIMPEZA DE TERRNOS NA LINHA DE TRANSMISSÃO.",
    STATUS: "EXPIRADA",
    IDMOV: 2010343,
    CENTRO_DE_CUSTO:
      "Construção SE 230/69KV/LT 230KV Leilão da ANEEL D.Pedro II",
  },
  {
    CODCCUSTO: "2.0363",
    NUMEROMOV: "271387",
    DATACRIACAO: "21 jul 2023",
    DATAENTREGA: "21 ago 2023",
    ATRASO: 138,
    CODTMV: "1.1.05",
    CODCFO: "47490",
    NOME: "TALAVEIRA, AVILA SOUZA LTDA - ME",
    USUARIOCRIACAO: "pedro.pestille",
    VALORLIQUIDOORIG: 1599.0,
    HISTORICOCURTO:
      "SUBSTITUIR CARDAN COMPLETO RA-05 ROÇADEIRA DE ASFALTO, RD-1500 C/ RODA, FROTA ENGEPAR, ATENDENDO OBRA BR-060 EQUIPE DE ROÇADA",
    STATUS: "EXPIRADA",
    IDMOV: 2010341,
    CENTRO_DE_CUSTO: "Manut./Recuperação/Conservação BR-060/MS DNIT",
  },
];
